name: Pack3d Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Tests
        run: go test ./... -short
